# Generated by Django 6.1.1 on 2026-09-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['type', 'position', 'id']},
        ),
        migrations.AddField(
            model_name='channel',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_style',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
