# Generated by Django 6.1.1 on 2026-09-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment_transcript',
            field=models.TextField(blank=True, default=''),
        ),
    ]
