# Generated by Django 6.1.1 on 2026-09-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_message_attachment_transcript'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AddField(
            model_name='server',
            name='icon_image',
            field=models.FileField(blank=True, null=True, upload_to='server_icons/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='server',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
